import { useEffect, useState } from "react";
import { Plus, Power, UserRoundCheck, Pencil } from "lucide-react";
import { toast } from "sonner";
import api from "@/lib/api";

const emptyPerms={customers:["view","manage"],drivers:["view","approve_reject"],vehicles:["view","approve_reject"],drop_places:["view","add","edit","enable_disable"],bookings:["view","manage_status","live_trip"],commission:["view","manage"],payments:["view","verify"],fares:["view","manage"],complaints:["view","manage"],reports:["view"]};
const areas=Object.keys(emptyPerms);
const blank=()=>({name:"",mobile:"",manager_id:"",password:"",pickup_pins:"",commission_pct:10,permissions:JSON.parse(JSON.stringify(emptyPerms)),active:true});
export default function ManagerAdminView(){
 const [rows,setRows]=useState([]),[show,setShow]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank());
 const [fareRows,setFareRows]=useState([]),[discount,setDiscount]=useState(0);
 const hdrs={headers:{"x-role":"admin"}};
 const load=async()=>{try{setRows((await api.get("/admin/managers",hdrs)).data)}catch(e){toast.error(e.response?.data?.detail||"Failed to load managers")}};
 useEffect(()=>{load()},[]);
 const openAdd=()=>{setEditing(null);setForm(blank());setShow(true)};
 const openEdit=async(m)=>{setEditing(m.id);setForm({name:m.name||"",mobile:m.mobile||"",manager_id:m.manager_id||"",password:"",pickup_pins:(m.pickup_pins||[]).join(", "),commission_pct:m.commission_pct??10,permissions:{...JSON.parse(JSON.stringify(emptyPerms)),...(m.permissions||{})},active:!!m.active});setShow(true);try{const [f,d]=await Promise.all([api.get(`/admin/manager-fare-settings/${m.id}`,hdrs),api.get(`/admin/manager-discounts/${m.id}`,hdrs)]);setFareRows(f.data);setDiscount(Number(d.data?.discount_pct||0))}catch(e){toast.error(e.response?.data?.detail||"Could not load manager fare settings")}};
 const save=async()=>{if(!form.name||!form.mobile||!form.manager_id)return toast.error("Name, mobile and Manager ID are required");try{if(editing){const body={pickup_pins:form.pickup_pins.split(",").map(x=>x.trim()).filter(Boolean),commission_pct:Number(form.commission_pct),permissions:form.permissions,active:form.active};await api.patch(`/admin/managers/${editing}`,body,hdrs);toast.success("Manager permissions updated")}else{if(!form.password)return toast.error("Password is required");await api.post("/admin/managers",{...form,pickup_pins:form.pickup_pins.split(",").map(x=>x.trim()).filter(Boolean),commission_pct:Number(form.commission_pct)},hdrs);toast.success("Manager added")}setShow(false);setEditing(null);load()}catch(e){toast.error(e.response?.data?.detail||"Save failed")}};
 const toggle=async m=>{try{await api.patch(`/admin/managers/${m.id}`,{active:!m.active},hdrs);load()}catch(e){toast.error(e.response?.data?.detail||"Failed")}};
 const resign=async m=>{if(!window.confirm(`Resign/deactivate ${m.name}?`))return;try{await api.patch(`/admin/managers/${m.id}`,{resigned:true},hdrs);load()}catch(e){toast.error(e.response?.data?.detail||"Failed")}};
 const setPerm=(area,perm,on)=>setForm(f=>({...f,permissions:{...f.permissions,[area]:on?[...(f.permissions[area]||[]),perm]:(f.permissions[area]||[]).filter(x=>x!==perm)}}));
 return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl font-bold">Managers</h2><p className="text-sm text-gray-500">Each Manager gets separate Pickup PINs and permissions.</p></div><button className="brand-btn" onClick={openAdd}><Plus className="h-4 w-4 inline"/> Add Manager</button></div>
 {show&&<div className="card space-y-3"><div className="font-semibold">{editing?"Edit Manager Permissions":"Add Manager"}</div><div className="grid md:grid-cols-2 gap-3">{[["Manager Name","name"],["Mobile","mobile"],["Manager ID","manager_id"]].map(([ph,k])=><input key={k} className="field" placeholder={ph} value={form[k]} disabled={!!editing&&k!=="name"} onChange={e=>setForm({...form,[k]:k==="mobile"?e.target.value.replace(/\D/g,"").slice(0,10):e.target.value})}/>)}{!editing&&<input className="field" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>}<input className="field" placeholder="Assigned Pickup PIN(s), comma separated" value={form.pickup_pins} onChange={e=>setForm({...form,pickup_pins:e.target.value})}/><input className="field" type="number" min="0" max="100" placeholder="Commission %" value={form.commission_pct} onChange={e=>setForm({...form,commission_pct:e.target.value})}/></div>
 <div><div className="font-semibold mb-2">Admin-controlled permissions</div><div className="grid md:grid-cols-2 gap-2">{areas.map(a=><div key={a} className="border rounded-xl p-3"><div className="font-semibold capitalize">{a.replace("_"," ")}</div><div className="flex flex-wrap gap-2 mt-2">{emptyPerms[a].map(p=><label key={p} className="text-xs flex gap-1 items-center"><input type="checkbox" checked={(form.permissions[a]||[]).includes(p)} onChange={e=>setPerm(a,p,e.target.checked)}/>{p}</label>)}</div></div>)}</div></div>{editing&&<div className="border rounded-xl p-3 space-y-3"><div className="font-semibold">Manager-wise Fare & Discount (Admin Only)</div><div className="grid md:grid-cols-4 gap-2">{["E-Rickshaw","Tata Ace","Tempo","Tractor"].map(v=>{const r=fareRows.find(x=>x.vehicle_type===v)||{base_fare:0,per_km:0,commission_pct:form.commission_pct};return <div key={v} className="border rounded-lg p-2"><div className="text-xs font-semibold mb-2">{v}</div><input className="field mb-2" type="number" placeholder="Base Fare" value={r.base_fare} onChange={e=>setFareRows(xs=>[...xs.filter(x=>x.vehicle_type!==v),{...r,vehicle_type:v,base_fare:Number(e.target.value)}])}/><input className="field" type="number" placeholder="Per KM" value={r.per_km} onChange={e=>setFareRows(xs=>[...xs.filter(x=>x.vehicle_type!==v),{...r,vehicle_type:v,per_km:Number(e.target.value)}])}/></div>})}<div className="border rounded-lg p-2"><div className="text-xs font-semibold mb-2">Discount (Manager-wise)</div><input className="field" type="number" min="0" max="100" value={discount} onChange={e=>setDiscount(Math.max(0,Math.min(100,Number(e.target.value))))}/><div className="text-xs text-gray-500 mt-2">Admin only. Manager cannot edit discount.</div></div></div><button className="h-10 px-4 rounded-lg bg-blue-50 text-blue-700" onClick={async()=>{try{for(const v of ["E-Rickshaw","Tata Ace","Tempo","Tractor"]){const r=fareRows.find(x=>x.vehicle_type===v);if(r) await api.put(`/admin/manager-fare-settings/${editing}/${encodeURIComponent(v)}`,{base_fare:Number(r.base_fare||0),per_km:Number(r.per_km||0),commission_pct:Number(r.commission_pct??form.commission_pct??10)},hdrs)}await api.put(`/admin/manager-discounts/${editing}`,{discount_pct:Number(discount)},hdrs);toast.success("Manager fare and discount saved")}catch(e){toast.error(e.response?.data?.detail||"Save failed")}}>Save Fare & Discount</button></div>}<div className="flex gap-2"><button className="brand-btn" onClick={save}>{editing?"Save Permissions":"Save Manager"}</button><button className="h-10 px-4 rounded-lg bg-gray-100" onClick={()=>setShow(false)}>Cancel</button></div></div>}
 <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500"><th className="py-2">Manager</th><th>Manager ID</th><th>Pickup PIN(s)</th><th>Commission</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(m=><tr key={m.id} className="border-t"><td className="py-3">{m.name}<div className="text-xs text-gray-400">{m.mobile}</div></td><td>{m.manager_id}</td><td>{(m.pickup_pins||[]).join(", ")}</td><td>{m.commission_pct}%</td><td>{m.resigned?"Resigned":m.active?"Active":"Inactive"}</td><td className="flex gap-2 py-2"><button className="h-9 px-3 rounded-lg bg-blue-50 text-blue-700" onClick={()=>openEdit(m)}><Pencil className="h-4 w-4 inline"/> Permissions</button><button className="h-9 px-3 rounded-lg bg-gray-100" onClick={()=>toggle(m)}><Power className="h-4 w-4 inline"/> {m.active?"Disable":"Enable"}</button>{!m.resigned&&<button className="h-9 px-3 rounded-lg bg-rose-50 text-rose-700" onClick={()=>resign(m)}><UserRoundCheck className="h-4 w-4 inline"/> Resign</button>}</td></tr>)}</tbody></table>{!rows.length&&<div className="text-gray-500 py-4">No managers yet.</div>}</div></div>
}
